namespace BotEngine.Windows
{
	public enum DEBUG_EVENT_CODE : uint
	{
		NO_EVENT,
		EXCEPTION_DEBUG_EVENT,
		CREATE_THREAD_DEBUG_EVENT,
		CREATE_PROCESS_DEBUG_EVENT,
		EXIT_THREAD_DEBUG_EVENT,
		EXIT_PROCESS_DEBUG_EVENT,
		LOAD_DLL_DEBUG_EVENT,
		UNLOAD_DLL_DEBUG_EVENT,
		OUTPUT_DEBUG_STRING_EVENT,
		RIP_EVENT
	}
}
